apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-artifact-storage
  namespace: rhtuser-jenkins
spec:
  resources:
    requests:
      storage: 4Gi
  # this should be RWX but cinder (standard SC) does not support it
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
