pipeline {
    agent { node { label "maven" } }
    parameters {
        string (name: 'INVOKER', defaultValue: 'Grega')
        string (name: 'BRANCH', defaultValue: 'main')
        booleanParam (name: 'RESTORE_MAVEN_CACHE', defaultValue: true)
        booleanParam (name: 'BACKUP_MAVEN_CACHE', defaultValue: false)
        booleanParam (name: 'SKIP_TESTS', defaultValue: false)
        string (name: 'TARGET_PROJECT', defaultValue: 'rhtuser-greeter')
    }
    environment {
        BRANCH_NAME = "${params.BRANCH}"
        TARGET_PROJECT = "${params.TARGET_PROJECT}"
        QUAY_CREDS = credentials('QUAY_IO_CREDS')
    }
    stages {
        stage("Ask which branch to clone if not set") {
            when {
                expression { params.BRANCH == '' }
            }
            steps {
                script {
                    timeout(time: 60, unit: "SECONDS") {
                        try {
                            def response = input(
                                message: "What is the branch to clone?",
                                ok: "Proceed",
                                parameters: [
                                    string(name: "BRANCH_NAME",
                                            description: "The name of the branch to clone (default is \"main\")",
                                            defaultValue: "main")
                                ]
                            )
                            BRANCH_NAME = response
                            echo "Got input response: ${response}"
                        } catch (exc) {
                            echo "User input timed out: ${exc}\nProceeding with defaults."
                        }
                    }
                    echo "After INPUT stage: cloning ${BRANCH_NAME}"
                }
            }
        }
        stage("Log start parameters") {
            steps {
                echo """
Hello ${params.INVOKER}, about to build Greeter service.

Using the following Quay.io credentials:
    username: ${QUAY_CREDS_USR}
    password: ${QUAY_CREDS_PSW}

Cloning branch "${BRANCH_NAME}"
                """
            }
        }
        stage ("Clone git repository") {
            steps {
                echo "Cloning branch ${BRANCH_NAME} from ${GIT_URL}"
                git url: "${GIT_URL}", branch: "${BRANCH_NAME}"
            }
        }
        stage ("Run unit & code coverage tests") {
            when {
                expression { params.SKIP_TESTS == false }
            }
            parallel {
                stage ("Run unit tests") {
                    agent { node { label "maven" } }
                    steps {
                        sh '''
                            if [ -e /cache/artifacts.tar.gz ] && [ "${RESTORE_MAVEN_CACHE}" = "true" ]; then
                                echo -n "Restoring maven cache..."
                                mkdir -p /home/jenkins/.m2/repository
                                tar xf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository
                                echo "done."
                            fi
                            ./mvnw test
                            if [ -d /cache ] && [ "${BACKUP_MAVEN_CACHE}" = "true" ]; then
                                echo -n "Backing up maven cache..."
                                tar cf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository ./
                                echo "done."
                            fi
                        '''
                    }
                }
                stage ("Run code coverage") {
                    agent { node { label "maven" } }
                    steps {
                        sh '''
                            if [ -e /cache/artifacts.tar.gz ] && [ "${RESTORE_MAVEN_CACHE}" = "true" ]; then
                                echo -n "Restoring maven cache..."
                                mkdir -p /home/jenkins/.m2/repository
                                tar xf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository
                                echo "done."
                            fi
                            ./mvnw verify
                            if [ -d /cache ] && [ "${BACKUP_MAVEN_CACHE}" = "true" ]; then
                                echo -n "Backing up maven cache..."
                                tar cf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository ./
                                echo "done."
                            fi
                        '''
                    }
                }
            }
        }
        /*
        stage("Build the Application Traditionally") {
            steps {
                sh '''
                    if [ -e /cache/artifacts.tar.gz ] && [ "${RESTORE_MAVEN_CACHE}" = "true" ]; then
                        echo -n "Restoring maven cache..."
                        mkdir -p /home/jenkins/.m2/repository
                        tar xf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository
                        echo "done."
                    fi
                    ./mvnw -DskipTests package
                    if [ -d /cache ] && [ "${BACKUP_MAVEN_CACHE}" = "true" ]; then
                        echo -n "Backing up maven cache..."
                        tar cf /cache/artifacts.tar.gz -C /home/jenkins/.m2/repository ./
                        echo "done."
                    fi
                '''
                archiveArtifacts 'target/*-runner.jar'
            }
        }
        */
        stage("Build the Application in its Target Project using a BuildConfig") {
            steps {
                sh '''
                    if [ -z "$(oc -n ${TARGET_PROJECT} get bc/greeter -o name)" ]; then
                        # buildconfig does not exist, create it and immediately cancel any builds
                        oc -n ${TARGET_PROJECT} new-build --name greeter --image-stream openjdk:21 --strategy source ${GIT_URL}#${BRANCH_NAME}
                        oc -n ${TARGET_PROJECT} cancel-build bc/greeter
                    fi
                    # patch the buildconfig to be incremental and have a runPolicy of SerialLatestOnly
                    oc -n ${TARGET_PROJECT} patch bc/greeter --type=merge -p '{"spec": {"runPolicy": "SerialLatestOnly", "strategy": {"sourceStrategy": {"incremental": true}}}}'
                    # start the build and follow the logs
                    oc -n ${TARGET_PROJECT} start-build -F bc/greeter
                    # what is this build's name?
                    BUILD_NAME="$(oc -n ${TARGET_PROJECT} get builds -l build=greeter --sort-by=metadata.creationTimestamp -o name | tail -n1)"
                    # did it succeed?
                    BUILD_STATUS="$(oc -n ${TARGET_PROJECT} get ${BUILD_NAME} -o jsonpath='{.status.phase}')"
                    if [ "${BUILD_STATUS}" != "Complete" ]; then
                        echo "ERROR: Build did not complete successfully: phase=${BUILD_STATUS}"
                        exit 1
                    else
                        echo "SUCCESS: Build completed."
                    fi
                '''
            }
        }
        stage("Deploy the Application if not yet there") {
            steps {
                sh '''
                    if [ -z "$(oc -n ${TARGET_PROJECT} get deploy/greeter -o name)" ]; then
                        # deployment does not exist, create it and expose it
                        oc -n ${TARGET_PROJECT} new-app --name greeter --image-stream greeter:latest
                        oc -n ${TARGET_PROJECT} expose svc/greeter
                    else
                        echo "Nothing to do, deployment already there and being updated."
                    fi
                '''
            }
        }
    }
}